name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  path_provider: 2.1.3 

  flutter_svg: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/rectangle_16.png
  - assets/images/rectangle_96.png
  - assets/images/rectangle_32.png
  - assets/images/rectangle_102.png
  - assets/images/rectangle_54.png
  - assets/images/rectangle_49.png
  - assets/images/rectangle_65.png
  - assets/images/rectangle_34.png
  - assets/images/rectangle_75.png
  - assets/images/rectangle_73.png
  - assets/images/rectangle_90.png
  - assets/images/rectangle_28.png
  - assets/images/rectangle_14.png
  - assets/images/rectangle_89.png
  - assets/images/rectangle_92.png
  - assets/images/rectangle_53.png
  - assets/images/rectangle_26.png
  - assets/images/rectangle_101.png
  - assets/images/rectangle_80.png
  - assets/images/rectangle_72.png
  - assets/images/rectangle_100.png
  - assets/images/rectangle_76.png
  - assets/images/rectangle_35.png
  - assets/images/rectangle_82.png
  - assets/images/rectangle_5.png
  - assets/images/rectangle_40.png
  - assets/images/rectangle_50.png
  - assets/images/rectangle_62.png
  - assets/images/rectangle_11.png
  - assets/images/rectangle_56.png
  - assets/images/rectangle_52.png
  - assets/images/rectangle_41.png
  - assets/images/rectangle_29.png
  - assets/images/rectangle_71.png
  - assets/images/rectangle_42.png
  - assets/images/rectangle_27.png
  - assets/images/rectangle_74.png
  - assets/images/rectangle_48.png
  - assets/images/rectangle_67.png
  - assets/images/rectangle_18.png
  - assets/images/rectangle_59.png
  - assets/images/rectangle_24.png
  - assets/images/rectangle_39.png
  - assets/images/rectangle_69.png
  - assets/images/rectangle_30.png
  - assets/images/rectangle_43.png
  - assets/images/rectangle_46.png
  - assets/images/rectangle_84.png
  - assets/images/rectangle_86.png
  - assets/images/rectangle_31.png
  - assets/images/rectangle_21.png
  - assets/images/rectangle_58.png
  - assets/images/rectangle_103.png
  - assets/images/rectangle_25.png
  - assets/images/rectangle_15.png
  - assets/images/rectangle_51.png
  - assets/images/rectangle_8.png
  - assets/images/rectangle_70.png
  - assets/images/rectangle_33.png
  - assets/images/rectangle_94.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/rectangle_12.png
  - assets/images/rectangle_85.png
  - assets/images/rectangle.png
  - assets/images/rectangle_61.png
  - assets/images/rectangle_66.png
  - assets/images/rectangle_36.png
  - assets/images/rectangle_78.png
  - assets/images/rectangle_79.png
  - assets/images/rectangle_17.png
  - assets/images/rectangle_60.png
  - assets/images/rectangle_9.png
  - assets/images/rectangle_38.png
  - assets/images/rectangle_2.png
  - assets/images/rectangle_20.png
  - assets/images/rectangle_55.png
  - assets/images/rectangle_10.png
  - assets/images/rectangle_6.png
  - assets/images/rectangle_19.png
  - assets/images/rectangle_1.png
  - assets/images/rectangle_13.png
  - assets/images/rectangle_88.png
  - assets/images/rectangle_22.png
  - assets/images/rectangle_57.png
  - assets/images/rectangle_68.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/rectangle_75.png
  - assets/images/rectangle_60.png
  - assets/images/rectangle_50.png
  - assets/images/rectangle_59.png
  - assets/images/rectangle.png
  - assets/images/rectangle_78.png
  - assets/images/rectangle_10.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png
  - assets/images/rectangle_57.png
  - assets/images/rectangle_22.png
  - assets/images/rectangle_70.png
  - assets/images/rectangle_100.png
  - assets/images/rectangle_84.png
  - assets/images/rectangle_58.png
  - assets/images/rectangle_52.png
  - assets/images/rectangle_12.png
  - assets/images/rectangle_26.png
  - assets/images/rectangle_17.png
  - assets/images/rectangle_102.png
  - assets/images/rectangle_61.png
  - assets/images/rectangle_41.png
  - assets/images/rectangle_21.png
  - assets/images/rectangle_65.png
  - assets/images/rectangle_14.png
  - assets/images/rectangle_103.png
  - assets/images/rectangle_20.png
  - assets/images/rectangle_101.png
  - assets/images/rectangle_94.png
  - assets/images/rectangle_36.png
  - assets/images/rectangle_5.png
  - assets/images/rectangle_49.png
  - assets/images/rectangle_28.png
  - assets/images/rectangle_6.png
  - assets/images/rectangle_32.png
  - assets/images/rectangle_39.png
  - assets/images/rectangle_51.png
  - assets/images/rectangle_89.png
  - assets/images/rectangle_68.png
  - assets/images/rectangle_16.png
  - assets/images/rectangle_25.png
  - assets/images/rectangle_18.png
  - assets/images/rectangle_24.png
  - assets/images/rectangle_11.png
  - assets/images/rectangle_35.png
  - assets/images/rectangle_62.png
  - assets/images/rectangle_43.png
  - assets/images/rectangle_92.png
  - assets/images/rectangle_82.png
  - assets/images/rectangle_55.png
  - assets/images/rectangle_53.png
  - assets/images/rectangle_54.png
  - assets/images/rectangle_72.png
  - assets/images/rectangle_9.png
  - assets/images/rectangle_15.png
  - assets/images/rectangle_19.png
  - assets/images/rectangle_79.png
  - assets/images/rectangle_85.png
  - assets/images/rectangle_96.png
  - assets/images/rectangle_40.png
  - assets/images/rectangle_8.png
  - assets/images/rectangle_73.png
  - assets/images/rectangle_33.png
  - assets/images/rectangle_76.png
  - assets/images/rectangle_42.png
  - assets/images/rectangle_69.png
  - assets/images/rectangle_48.png
  - assets/images/rectangle_74.png
  - assets/images/rectangle_31.png
  - assets/images/rectangle_86.png
  - assets/images/rectangle_88.png
  - assets/images/rectangle_1.png
  - assets/images/rectangle_30.png
  - assets/images/rectangle_38.png
  - assets/images/rectangle_66.png
  - assets/images/rectangle_2.png
  - assets/images/rectangle_46.png
  - assets/images/rectangle_56.png
  - assets/images/rectangle_67.png
  - assets/images/rectangle_80.png
  - assets/images/rectangle_29.png
  - assets/images/rectangle_71.png
  - assets/images/rectangle_90.png
  - assets/images/rectangle_13.png
  - assets/images/rectangle_27.png
  - assets/images/rectangle_34.png
  - assets/images/green_circular_farm_organic_wheat_agriculture_farming_logo_2024053014221800001.png